version = 1

test_patterns = ["tests/**"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/tinygo-org/tinygo"]

[[transformers]]
name = "gofmt"
enabled = true
